export const ADD_CONTENT = 'ADD_CONTENT';
export const GET_CONTENT = 'GET_CONTENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const DELETE_CONTENT = 'DELETE_CONTENT';

export const TOGGLE_LATEST = 'TOGGLE_LATEST';
export const TOGGLE_OLDEST = 'TOGGLE_OLDEST';

export const ADD_TO_HISTORY = "ADD_TO_HISTORY";

